[providers]
providers = ["python"]

[variables]
PYTHONPATH = "/app"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "pip install uwsgi"
]

[phases.build]
cmds = [
  "python -m compileall -q searx"
]

[start]
cmd = "uwsgi --http-socket 0.0.0.0:$PORT --module searx.webapp --callable app --workers 2 --threads 2 --master --die-on-term" 